import type { Metadata } from 'next'
import localFont from 'next/font/local'

import Base from '@/components/layouts/Base'
import '@/styles/index.css'

export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'Create Next App'
}

const louisGeorgeCafeLight = localFont({
	src: '../styles/fonts/LouisGeorgeCafeLight.ttf'
})

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html data-lt-installed='true' lang='fr' suppressHydrationWarning>
			<body className={`${louisGeorgeCafeLight.className} antialiased`}>
				<Base>{children}</Base>
			</body>
		</html>
	)
}
