import Base from '@/components/layouts/Base'
import '@/i18n/index'
import '@/styles/index.css'

import type { Metadata } from 'next'

export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'Create Next App'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html data-lt-installed='true' lang='fr' suppressHydrationWarning>
			<body className='font-louisGeorgeCafe-light antialiased'>
				<Base>{children}</Base>
			</body>
		</html>
	)
}
