import { getT } from '@/app/i18n'
import { languages } from '@/app/i18n/settings'
import Base from '@/components/layouts/Base'
import '@/app/i18n/client'
import '@/styles/index.css'
import 'jotai-devtools/styles.css'

export async function generateStaticParams() {
	return languages.map((lng) => ({ lng }))
}

export async function generateMetadata() {
	const { t } = await getT()
	return {
		description: 'Generated by create next app',
		title: t('common:login')
	}
}
export default function RootLayout({ children, params: { lng } }) {
	return (
		<html data-lt-installed='true' lang={lng} suppressHydrationWarning>
			<body className='font-louisGeorgeCafe-light antialiased' suppressHydrationWarning>
				<Base>{children}</Base>
			</body>
		</html>
	)
}
