import { getT } from '@/app/i18n'
import '@/app/i18n/client'

import { languages } from '@/app/i18n/settings'
import Base from '@/components/layouts/Base'
import '@/styles/index.css'
import 'jotai-devtools/styles.css'

import { use } from 'react'
import { ToastContainer } from 'react-toastify'

export async function generateStaticParams() {
	return languages.map((lng) => ({ lng }))
}

export async function generateMetadata() {
	const { t } = await getT()

	return {
		description: 'Generated by create next app',
		title: t('common:login')
	}
}

export default function RootLayout({ children, params }) {
	const { lng } = use(params) as { lng: string }

	return (
		<html data-lt-installed='true' lang={lng} suppressHydrationWarning>
			<body className='font-louisGeorgeCafe-light antialiased' suppressHydrationWarning>
				<Base>{children}</Base>
				<ToastContainer
					autoClose={2000}
					hideProgressBar
					icon={false}
					toastStyle={{
						borderRadius: '10px',
						boxShadow: '0 4px 12px rgba(0, 0, 0, 0.4)',
						color: '#121212'
					}}
				/>
			</body>
		</html>
	)
}
