import { languages } from '@/app/i18n/settings'
import Base from '@/components/layouts/Base'
import '@/app/i18n/client'
import '@/styles/index.css'
import 'jotai-devtools/styles.css'

import type { Metadata } from 'next'

import Base from '@/components/layouts/Base'

export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'Create Next App'
}

export async function generateStaticParams() {
	return languages.map((lng) => ({ lng }))
}

export default function RootLayout({ children, params: { lng } }) {
	return (
		<html data-lt-installed='true' lang={lng} suppressHydrationWarning>
			<body className='font-louisGeorgeCafe-light antialiased'>
				<Base>{children}</Base>
			</body>
		</html>
	)
}
